/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HireIndexRouteImport } from './routes/hire/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as HireCategoryRouteImport } from './routes/hire/$category'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard/quotes'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardEventsRouteImport } from './routes/dashboard/events'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HireIndexRoute = HireIndexRouteImport.update({
  id: '/hire/',
  path: '/hire/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const HireCategoryRoute = HireCategoryRouteImport.update({
  id: '/hire/$category',
  path: '/hire/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/hire/$category': typeof HireCategoryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/hire/': typeof HireIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/hire/$category': typeof HireCategoryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/hire': typeof HireIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/hire/$category': typeof HireCategoryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/hire/': typeof HireIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultation'
    | '/contact'
    | '/corporate'
    | '/dashboard'
    | '/gallery'
    | '/quote'
    | '/services'
    | '/dashboard/bookings'
    | '/dashboard/events'
    | '/dashboard/inventory'
    | '/dashboard/leads'
    | '/dashboard/quotes'
    | '/dashboard/reports'
    | '/hire/$category'
    | '/dashboard/'
    | '/hire/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultation'
    | '/contact'
    | '/corporate'
    | '/gallery'
    | '/quote'
    | '/services'
    | '/dashboard/bookings'
    | '/dashboard/events'
    | '/dashboard/inventory'
    | '/dashboard/leads'
    | '/dashboard/quotes'
    | '/dashboard/reports'
    | '/hire/$category'
    | '/dashboard'
    | '/hire'
  id:
    | '__root__'
    | '/'
    | '/consultation'
    | '/contact'
    | '/corporate'
    | '/dashboard'
    | '/gallery'
    | '/quote'
    | '/services'
    | '/dashboard/bookings'
    | '/dashboard/events'
    | '/dashboard/inventory'
    | '/dashboard/leads'
    | '/dashboard/quotes'
    | '/dashboard/reports'
    | '/hire/$category'
    | '/dashboard/'
    | '/hire/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  HireCategoryRoute: typeof HireCategoryRoute
  HireIndexRoute: typeof HireIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/': {
      id: '/hire/'
      path: '/hire'
      fullPath: '/hire/'
      preLoaderRoute: typeof HireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/hire/$category': {
      id: '/hire/$category'
      path: '/hire/$category'
      fullPath: '/hire/$category'
      preLoaderRoute: typeof HireCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GalleryRoute: GalleryRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  HireCategoryRoute: HireCategoryRoute,
  HireIndexRoute: HireIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
